/**
 * Schema migrations — SPEC §6.2, transcribed.
 *
 * Written as raw SQL rather than generated by drizzle-kit, for one specific reason
 * §4.6 states outright: **Drizzle cannot model FTS5 virtual tables**, and the FTS5
 * setup here is not incidental — the external-content table, the explicit rowid, and
 * the three triggers are load-bearing and were each wrong once (Appendix C, defect 5).
 * Hand-written SQL keeps them verbatim and reviewable against the spec.
 *
 * Drizzle still provides typed queries over these tables (`schema.ts`); it just is not
 * the source of truth for their DDL.
 *
 * Versioning uses `PRAGMA user_version`. Each entry runs exactly once, in order.
 */

export interface Migration {
  version: number;
  name: string;
  statements: string[];
}

export const MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'initial',
    statements: [
      `CREATE TABLE speakers (
         id TEXT PRIMARY KEY, name TEXT NOT NULL, sort_name TEXT NOT NULL,
         role TEXT NOT NULL, succession_order INTEGER,
         aliases TEXT NOT NULL DEFAULT '[]',
         photo_path TEXT, gradient_seed TEXT NOT NULL, bio TEXT
       )`,

      `CREATE TABLE series (
         id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'other',
         speaker_id TEXT REFERENCES speakers(id), description TEXT,
         artwork_path TEXT, total_parts INTEGER
       )`,

      // ⚠️ rowid is EXPLICIT and INTEGER PRIMARY KEY. Mandatory: the FTS5
      // external-content table maps on rowid, and SQLite may renumber implicit rowids
      // during VACUUM — which silently corrupts the search index. `id` stays the
      // stable public key.
      `CREATE TABLE talks (
         rowid INTEGER PRIMARY KEY,
         id TEXT NOT NULL UNIQUE,
         content_hash TEXT NOT NULL,
         title TEXT NOT NULL, subtitle TEXT,
         speaker_id TEXT REFERENCES speakers(id),
         speaker_name TEXT NOT NULL DEFAULT '',
         series_id TEXT REFERENCES series(id), part_number INTEGER,
         duration_sec INTEGER, published_at INTEGER, recorded_year INTEGER,
         event_name TEXT, session_name TEXT,
         archive_path TEXT NOT NULL, stream_path TEXT,
         size_bytes INTEGER NOT NULL, stream_size_bytes INTEGER,
         mime_type TEXT NOT NULL,
         artwork_path TEXT, artwork_color TEXT,
         transcript TEXT, transcript_source TEXT, source_url TEXT,
         source TEXT NOT NULL, imported_at INTEGER NOT NULL,
         original_paths TEXT NOT NULL DEFAULT '[]',
         parse_confidence REAL NOT NULL DEFAULT 1.0,
         flags TEXT NOT NULL DEFAULT '[]',
         missing_since INTEGER
       )`,
      `CREATE INDEX idx_talks_speaker ON talks(speaker_id, published_at DESC)`,
      `CREATE INDEX idx_talks_series ON talks(series_id, part_number)`,
      `CREATE INDEX idx_talks_year ON talks(recorded_year DESC)`,
      `CREATE INDEX idx_talks_missing ON talks(missing_since) WHERE missing_since IS NOT NULL`,
      `CREATE INDEX idx_talks_attention ON talks(parse_confidence) WHERE parse_confidence < 0.7`,
      `CREATE UNIQUE INDEX idx_talks_hash ON talks(content_hash)`,

      // `origin` governs deletion authority: catalog sync may only remove
      // origin='catalog' rows, so every device-created row survives every sync (§12.1).
      `CREATE TABLE collections (
         id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT,
         kind TEXT NOT NULL DEFAULT 'user',
         origin TEXT NOT NULL DEFAULT 'device',
         icon TEXT, color TEXT,
         sort_order INTEGER NOT NULL DEFAULT 0,
         parent_id TEXT REFERENCES collections(id),
         smart_query TEXT, pinned INTEGER NOT NULL DEFAULT 0,
         updated_at INTEGER NOT NULL, deleted_at INTEGER, device_id TEXT NOT NULL
       )`,
      `CREATE INDEX idx_coll_parent ON collections(parent_id, sort_order) WHERE deleted_at IS NULL`,

      // ⚠️ NO `ON DELETE CASCADE` anywhere on syncable tables. Cascades turn a
      // transient catalog shrink into permanent loss of the user's ratings and curation.
      `CREATE TABLE collection_members (
         collection_id TEXT NOT NULL REFERENCES collections(id),
         talk_id       TEXT NOT NULL REFERENCES talks(id),
         order_key     TEXT NOT NULL,
         origin        TEXT NOT NULL DEFAULT 'device',
         added_at      INTEGER NOT NULL,
         updated_at    INTEGER NOT NULL, deleted_at INTEGER, device_id TEXT NOT NULL,
         PRIMARY KEY (collection_id, talk_id)
       )`,
      `CREATE INDEX idx_cm_order ON collection_members(collection_id, order_key, talk_id) WHERE deleted_at IS NULL`,
      `CREATE INDEX idx_cm_talk ON collection_members(talk_id) WHERE deleted_at IS NULL`,

      `CREATE TABLE tags (
         id TEXT PRIMARY KEY, name TEXT NOT NULL, color TEXT,
         kind TEXT NOT NULL DEFAULT 'user', origin TEXT NOT NULL DEFAULT 'device',
         updated_at INTEGER NOT NULL, deleted_at INTEGER, device_id TEXT NOT NULL
       )`,
      `CREATE UNIQUE INDEX idx_tags_name ON tags(name) WHERE deleted_at IS NULL`,

      `CREATE TABLE talk_tags (
         talk_id TEXT NOT NULL REFERENCES talks(id),
         tag_id  TEXT NOT NULL REFERENCES tags(id),
         origin  TEXT NOT NULL DEFAULT 'device',
         updated_at INTEGER NOT NULL, deleted_at INTEGER, device_id TEXT NOT NULL,
         PRIMARY KEY (talk_id, tag_id)
       )`,
      `CREATE INDEX idx_tt_tag ON talk_tags(tag_id, talk_id) WHERE deleted_at IS NULL`,

      `CREATE TABLE listen_state (
         talk_id TEXT PRIMARY KEY REFERENCES talks(id) ON DELETE CASCADE,
         position_sec REAL NOT NULL DEFAULT 0,
         played INTEGER NOT NULL DEFAULT 0,
         play_count INTEGER NOT NULL DEFAULT 0,
         completed_at INTEGER, rating INTEGER, favorite INTEGER NOT NULL DEFAULT 0,
         note TEXT, updated_at INTEGER NOT NULL, device_id TEXT NOT NULL
       )`,
      `CREATE INDEX idx_listen_unplayed ON listen_state(played, updated_at DESC)`,
      `CREATE INDEX idx_listen_rating ON listen_state(rating DESC) WHERE rating IS NOT NULL`,

      `CREATE TABLE bookmarks (
         id TEXT PRIMARY KEY, talk_id TEXT NOT NULL REFERENCES talks(id),
         position_sec REAL NOT NULL, label TEXT, note TEXT, created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL, deleted_at INTEGER, device_id TEXT NOT NULL
       )`,
      `CREATE INDEX idx_bm_talk ON bookmarks(talk_id, position_sec) WHERE deleted_at IS NULL`,

      // Local-only. NOT synced, NOT in state.json. Rebuildable from disk at any time.
      `CREATE TABLE cache_entries (
         talk_id TEXT NOT NULL REFERENCES talks(id),
         rendition TEXT NOT NULL,
         local_path TEXT NOT NULL, bytes INTEGER NOT NULL DEFAULT 0,
         content_length INTEGER NOT NULL DEFAULT 0,
         state TEXT NOT NULL DEFAULT 'pending',
         pinned INTEGER NOT NULL DEFAULT 0,
         last_played_at INTEGER NOT NULL DEFAULT 0,
         downloaded_at INTEGER NOT NULL DEFAULT 0,
         attempts INTEGER NOT NULL DEFAULT 0,
         PRIMARY KEY (talk_id, rendition)
       )`,
      // Eviction order = least-recently-*touched*, where a never-played download falls
      // back to its download time. Sorting on last_played_at alone evicts the preloads
      // and download-for-later items first — exactly backwards (§11.3 rule 1).
      `CREATE INDEX idx_cache_lru ON cache_entries(pinned, last_played_at, downloaded_at)`,

      // Fractional order_key, same scheme as collection_members — the queue is
      // drag-reorderable, so an INTEGER position would need renumbering on every move.
      `CREATE TABLE queue (
         talk_id   TEXT PRIMARY KEY REFERENCES talks(id),
         order_key TEXT NOT NULL,
         added_at  INTEGER NOT NULL
       )`,
      `CREATE INDEX idx_queue_order ON queue(order_key, talk_id)`,

      // Sync outbox. Every mutation writes here in the SAME transaction, and the
      // flusher READS the payloads — it is the change-set, not a dirty flag (§12.2).
      `CREATE TABLE outbox (
         id TEXT PRIMARY KEY, entity TEXT NOT NULL, entity_id TEXT NOT NULL,
         op TEXT NOT NULL,
         payload TEXT NOT NULL,
         created_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0
       )`,
      `CREATE INDEX idx_outbox_order ON outbox(created_at)`,

      `CREATE TABLE sync_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)`,

      // ── FTS5 ────────────────────────────────────────────────────────────────
      // External-content: no text duplication, but the contentless columns MUST all
      // exist on `talks`, because FTS5 issues
      // `SELECT title, transcript, speaker_name FROM talks WHERE rowid = ?`
      // for rebuild, integrity-check, snippet() and highlight().
      `CREATE VIRTUAL TABLE talks_fts USING fts5(
         title, transcript, speaker_name,
         content='talks', content_rowid='rowid',
         tokenize='unicode61 remove_diacritics 2'
       )`,

      // ⚠️ The 'delete' command BEFORE every update/delete is mandatory. Omitting it is
      // the single most common cause of a corrupt external-content FTS5 index.
      `CREATE TRIGGER talks_ai AFTER INSERT ON talks BEGIN
         INSERT INTO talks_fts(rowid, title, transcript, speaker_name)
         VALUES (new.rowid, new.title, new.transcript, new.speaker_name);
       END`,
      `CREATE TRIGGER talks_ad AFTER DELETE ON talks BEGIN
         INSERT INTO talks_fts(talks_fts, rowid, title, transcript, speaker_name)
         VALUES ('delete', old.rowid, old.title, old.transcript, old.speaker_name);
       END`,
      `CREATE TRIGGER talks_au AFTER UPDATE ON talks BEGIN
         INSERT INTO talks_fts(talks_fts, rowid, title, transcript, speaker_name)
         VALUES ('delete', old.rowid, old.title, old.transcript, old.speaker_name);
         INSERT INTO talks_fts(rowid, title, transcript, speaker_name)
         VALUES (new.rowid, new.title, new.transcript, new.speaker_name);
       END`,
    ],
  },
];

export const LATEST_VERSION = MIGRATIONS.reduce((max, m) => Math.max(max, m.version), 0);
