const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Signs release builds with `feast-release.jks` instead of Expo's default.
 *
 * ⚠️ WHY THIS EXISTS, AND WHY IT MUST NOT BE REMOVED
 *
 * Expo's generated `android/app/build.gradle` points the *release* build type at
 * `signingConfigs.debug`. The debug keystore is generated per machine and is not in
 * version control, so every "release" build from a fresh checkout would be signed by a
 * different key. Android identifies an app by (package name + signing key): install an
 * APK signed by a different key over an existing one and it refuses with
 * INSTALL_FAILED_UPDATE_INCOMPATIBLE. The only way past that is uninstalling — which
 * deletes the database, and with it every rating, bookmark, collection, and listening
 * position the user has accumulated.
 *
 * So the signing key is not a build detail. It is the thing that makes in-place updates
 * possible at all, which is the entire point of the update button.
 *
 * `android/` is regenerated by `expo prebuild`, so this cannot be a hand-edit to
 * build.gradle — it has to be a plugin that re-applies on every prebuild.
 *
 * Credentials come from `apps/mobile/keystore.properties`, which is gitignored. If it
 * is missing the build falls back to the debug key rather than failing, so a fresh
 * clone can still build something runnable; `publish-update.bat` refuses to publish in
 * that state, which is the right place for that check.
 */
const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    if (gradle.includes('feastReleaseSigning')) return cfg;

    // `rootProject` is android/, so ../ resolves to apps/mobile/.
    const signingBlock = `
    // feastReleaseSigning — injected by plugins/withReleaseSigning.js
    def feastKeystoreProps = new Properties()
    def feastKeystoreFile = rootProject.file("../keystore.properties")
    if (feastKeystoreFile.exists()) {
        feastKeystoreFile.withInputStream { feastKeystoreProps.load(it) }
    }
`;

    // 1. Load the properties just inside `android {`.
    gradle = gradle.replace(/android\s*\{/, (m) => `${m}\n${signingBlock}`);

    // 2. Add a `release` signing config next to Expo's `debug` one.
    gradle = gradle.replace(
      /signingConfigs\s*\{/,
      (m) => `${m}
        release {
            if (feastKeystoreFile.exists()) {
                storeFile rootProject.file("../" + feastKeystoreProps['storeFile'])
                storePassword feastKeystoreProps['storePassword']
                keyAlias feastKeystoreProps['keyAlias']
                keyPassword feastKeystoreProps['keyPassword']
            }
        }`,
    );

    // 3. Point the release BUILD TYPE at it.
    //
    //    ⚠️ This must be anchored on `buildTypes`. The word "release" appears first
    //    inside the `signingConfigs` block added above, and a pattern that merely
    //    looks for `release {` then the next `signingConfig signingConfigs.debug`
    //    runs straight past it and rewrites the *debug* build type instead — giving
    //    debug the release key and leaving release on the debug key, which is exactly
    //    backwards and silently produces unshippable APKs.
    gradle = gradle.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
      (_m, head) =>
        `${head}signingConfig feastKeystoreFile.exists() ? signingConfigs.release : signingConfigs.debug`,
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });

module.exports = withReleaseSigning;
